version: "3"

services:
  fastapi:
    build: fastapi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    platform: linux/amd64
    container_name: fastapi

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    links:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge